### ISSUE TITLE
What features to be built

### ISSUE THREAD

**Issue by chrsep** [statmin/statmin#2]
I was thinking that this would be important features of this project:
- Managing multiple repo/blog/website
- Managing all post in the website
- Extensibility (able to extend beyond jekyll and github, such as to gitlab/bitbucket and middleman/hugo/hexo/etc... with custom CI/CD setup)
- beautiful responsive efficient UI design

Other less important features:
- Multi account support

**Comment by alvintheodora** [comment]
Sugoi

**Comment by alvintheodora** [comment]
Looks great.

**Comment by chrsep** [comment]
I'll put this into readme
